hostname = '127.0.0.1'
hostport = '8888'
output = 'output'

[application]
dbtype = 'sqlite'
fsrarid = ''
license = 'f7bc886d-bbcd-4ce9-845f-1209d87d406d'

[config]
dbname = ''
driver = 'sqlite'
file = ''

[layouts]
timelayout = '2006-01-02T15:04:05-0700'
timelayoutclear = '2006.01.02 15:04:05'
timelayoutday = '2006.01.02'
timelayoututc = '2006-01-02T15:04:05'

[selfdb]
dbname = 'korrectkm'
driver = 'sqlite'
file = '.korrectkm\korrectkm.db'

[trueclient]
deviceid = '5c4cfe79-1439-465a-b376-3339b36ced07'
hashkey = 'c05850bd845b9dd6683f11635f50f73ef3a83130'
layoututc = '2006-01-02T15:04:05'
omsid = '32539e31-c671-4462-8443-3d92b038b0f9'
standgis = 'markirovka.crpt.ru'
standsuz = 'suzgrid.crpt.ru'
test = true
testgis = 'markirovka.sandbox.crptech.ru'
testsuz = 'suz.sandbox.crptech.ru'
useconfigdb = true

[trueznak]
dbname = ''
driver = 'sqlite'
file = ''
